# Generated by Django 3.0.3 on 2020-03-27 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlayer',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Player')),
                ('team', models.CharField(blank=True, max_length=32, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_player', to='players.Player')),
            ],
            bases=('players.player',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=32)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('team_a', models.CharField(blank=True, max_length=32, null=True)),
                ('team_b', models.CharField(blank=True, max_length=32, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(blank=True, to='events.EventPlayer')),
            ],
        ),
    ]
