# Generated by Django 3.0.3 on 2020-04-23 18:15

from django.db import migrations, models
import django.db.models.deletion


def update_events(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.object.all():
        event.completed = 'F'
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200404_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='completed',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'Pending'), ('F', 'Finished')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='eventplayer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_player', to='events.Event'),
        ),
        migrations.RunPython(update_events)
    ]
